## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt_packages:
    - libglpk-dev
    - libgmp-dev

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("MOBC"); Pkg.test("MOBC"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("MOBC")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MOBC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
